name: azkar
description: "Ethiopian Morning Adhkar app with Arabic text, Amharic translation, audio, counters, and reminders."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/azkar.png"
  image_path: "assets/icons/azkar.png"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/azkar.png